# Generated by Django 5.0.6 on 2024-05-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('ethnic_group', models.CharField(max_length=10)),
                ('parent_education', models.CharField(max_length=50)),
                ('lunch_type', models.CharField(max_length=20)),
                ('test_prep', models.CharField(max_length=20)),
                ('math_score', models.IntegerField()),
                ('reading_score', models.IntegerField()),
                ('writing_score', models.IntegerField()),
                ('result_label', models.CharField(max_length=20)),
            ],
        ),
    ]
