# Generated by Django 5.0.6 on 2024-05-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='student_name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
