# Generated by Django 5.0.6 on 2024-05-25 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_examresult_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresult',
            name='student_name',
        ),
    ]
